import { createTheme, ThemeOptions } from '@mui/material/styles';
import { typography } from './typography';
import { palette } from './palette';
import {
  AccordionTheme,
  AccordionActionsTheme,
  AccordionDetailsTheme,
  AccordionSummaryTheme,
  AlertTheme,
  AlertTitleTheme,
  AppBarTheme,
  AutocompleteTheme,
  AvatarTheme,
  AvatarGroupTheme,
  BackdropTheme,
  BadgeTheme,
  BottomNavigationTheme,
  BottomNavigationActionTheme,
  BreadcrumbsTheme,
  ButtonTheme,
  ButtonBaseTheme,
  ButtonGroupTheme,
  CardTheme,
  CardActionAreaTheme,
  CardActionsTheme,
  CardContentTheme,
  CardHeaderTheme,
  CardMediaTheme,
  CheckboxTheme,
  ChipTheme,
  FilledInputTheme,
  FormControlTheme,
  FormControlLabelTheme,
  FormGroupTheme,
  FormHelperTextTheme,
  FormLabelTheme,
  IconButtonTheme,
  TextFieldTheme,
  InputTheme,
  InputBaseTheme,
  InputAdornmentTheme,
  InputLabelTheme,
  ListTheme,
  ListItemTheme,
  ListItemTextTheme,
  ListSubheaderTheme,
  ListItemAvatarTheme,
  ListItemSecondaryActionTheme,
  ListItemIconTheme,
  ListItemButtonTheme,
  MenuTheme,
  MenuItemTheme,
  MenuListTheme,
  OutlinedInputTheme,
  RadioTheme,
  RadioGroupTheme,
  SelectTheme,
  SwitchTheme,
  TableTheme,
  TableBodyTheme,
  TableCellTheme,
  TableContainerTheme,
  TableFooterTheme,
  TableHeadTheme,
  TablePaginationTheme,
  TableRowTheme,
  TableSortLabelTheme,
  CircularProgressTheme,
  LinearProgressTheme,
  CollapseTheme,
  ContainerTheme,
  DividerTheme,
  DialogTheme,
  DialogActionsTheme,
  DialogContentTheme,
  DialogContentTextTheme,
  DialogTitleTheme,
  ToolbarTheme,
  DrawerTheme,
  FabTheme,
  GridTheme,
  ImageListTheme,
  ImageListItemTheme,
  ImageListItemBarTheme,
  LinkTheme,
  ModalTheme,
  NativeSelectTheme,
  PaginationTheme,
  PaginationItemTheme,
  PaperTheme,
  PopperTheme,
  PopoverTheme,
  RatingTheme,
  SkeletonTheme,
  SliderTheme,
  SnackbarTheme,
  SnackbarContentTheme,
  StackTheme,
  SpeedDialTheme,
  SpeedDialActionTheme,
  SpeedDialIconTheme,
  StepTheme,
  StepButtonTheme,
  StepConnectorTheme,
  StepContentTheme,
  StepIconTheme,
  StepLabelTheme,
  StepperTheme,
  SvgIconTheme,
  SwipeableDrawerTheme,
  TabTheme,
  TabsTheme,
  ToggleButtonTheme,
  ToggleButtonGroupTheme,
  TooltipTheme,
  TypographyTheme,
} from '../components';

declare module '@mui/material/styles' {
  interface BreakpointOverrides {
    xs: true;
    sm: true;
    md: true;
    lg: true;
    xl: true;
    xxl: true;
  }
}
export const defaultTheme: ThemeOptions = {
  breakpoints: {
    keys: [`xs`, `sm`, `md`, `lg`, `xl`, `xxl`],
    values: {
      xs: 0,
      sm: 600,
      md: 840,
      lg: 1024,
      xl: 1280,
      xxl: 1440,
    },
  },
  palette,
  typography,
  spacing: 8,
  shape: {
    borderRadius: 3,
  },
};

export const overrideComponents = (theme: any) => {
  return {
    MuiAccordion: { ...AccordionTheme(theme) },
    MuiAccordionActions: { ...AccordionActionsTheme(theme) },
    MuiAccordionDetails: { ...AccordionDetailsTheme(theme) },
    MuiAccordionSummary: { ...AccordionSummaryTheme(theme) },
    MuiAlert: { ...AlertTheme(theme) },
    MuiAlertTitle: { ...AlertTitleTheme(theme) },
    MuiAppBar: { ...AppBarTheme(theme) },
    MuiAutocomplete: { ...AutocompleteTheme(theme) },
    MuiAvatar: { ...AvatarTheme(theme) },
    MuiAvatarGroup: { ...AvatarGroupTheme(theme) },
    MuiBackdrop: { ...BackdropTheme(theme) },
    MuiBadge: { ...BadgeTheme(theme) },
    MuiBottomNavigation: { ...BottomNavigationTheme(theme) },
    MuiBottomNavigationAction: { ...BottomNavigationActionTheme(theme) },
    MuiBreadcrumbs: { ...BreadcrumbsTheme(theme) },
    MuiButton: { ...ButtonTheme(theme) },
    MuiButtonBase: { ...ButtonBaseTheme(theme) },
    MuiButtonGroup: { ...ButtonGroupTheme(theme) },
    MuiCard: { ...CardTheme(theme) },
    MuiCardActionArea: { ...CardActionAreaTheme(theme) },
    MuiCardActions: { ...CardActionsTheme(theme) },
    MuiCardContent: { ...CardContentTheme(theme) },
    MuiCardHeader: { ...CardHeaderTheme(theme) },
    MuiCardMedia: { ...CardMediaTheme(theme) },
    MuiCheckbox: { ...CheckboxTheme(theme) },
    MuiChip: { ...ChipTheme(theme) },
    MuiCircularProgress: { ...CircularProgressTheme(theme) },
    MuiCollapse: { ...CollapseTheme(theme) },
    MuiContainer: { ...ContainerTheme(theme) },
    MuiDialog: { ...DialogTheme(theme) },
    MuiDialogActions: { ...DialogActionsTheme(theme) },
    MuiDialogContent: { ...DialogContentTheme(theme) },
    MuiDialogContentText: { ...DialogContentTextTheme(theme) },
    MuiDialogTitle: { ...DialogTitleTheme(theme) },
    MuiDivider: { ...DividerTheme(theme) },
    MuiDrawer: { ...DrawerTheme(theme) },
    MuiFab: { ...FabTheme(theme) },
    MuiFilledInput: { ...FilledInputTheme(theme) },
    MuiFormControl: { ...FormControlTheme(theme) },
    MuiFormControlLabel: { ...FormControlLabelTheme(theme) },
    MuiFormGroup: { ...FormGroupTheme(theme) },
    MuiFormHelperText: { ...FormHelperTextTheme(theme) },
    MuiFormLabel: { ...FormLabelTheme(theme) },
    MuiGrid: { ...GridTheme(theme) },
    MuiIconButton: { ...IconButtonTheme(theme) },
    MuiImageList: { ...ImageListTheme(theme) },
    MuiImageListItem: { ...ImageListItemTheme(theme) },
    MuiImageListItemBar: { ...ImageListItemBarTheme(theme) },
    MuiInput: { ...InputTheme(theme) },
    MuiInputAdornment: { ...InputAdornmentTheme(theme) },
    MuiInputBase: { ...InputBaseTheme(theme) },
    MuiInputLabel: { ...InputLabelTheme(theme) },
    MuiLinearProgress: { ...LinearProgressTheme(theme) },
    MuiLink: { ...LinkTheme(theme) },
    MuiList: { ...ListTheme(theme) },
    MuiListItem: { ...ListItemTheme(theme) },
    MuiListItemAvatar: { ...ListItemAvatarTheme(theme) },
    MuiListItemButton: { ...ListItemButtonTheme(theme) },
    MuiListItemIcon: { ...ListItemIconTheme(theme) },
    MuiListItemSecondaryAction: {
      ...ListItemSecondaryActionTheme(theme),
    },
    MuiListItemText: { ...ListItemTextTheme(theme) },
    MuiListSubheader: { ...ListSubheaderTheme(theme) },
    MuiMenu: { ...MenuTheme(theme) },
    MuiMenuItem: { ...MenuItemTheme(theme) },
    MuiMenuList: { ...MenuListTheme(theme) },
    MuiModal: { ...ModalTheme(theme) },
    MuiNativeSelect: { ...NativeSelectTheme(theme) },
    MuiOutlinedInput: { ...OutlinedInputTheme(theme) },
    MuiPagination: { ...PaginationTheme(theme) },
    MuiPaginationItem: { ...PaginationItemTheme(theme) },
    MuiPaper: { ...PaperTheme(theme) },
    MuiPopover: { ...PopoverTheme(theme) },
    MuiPopper: { ...PopperTheme(theme) },
    MuiRadio: { ...RadioTheme(theme) },
    MuiRadioGroup: { ...RadioGroupTheme(theme) },
    MuiRating: { ...RatingTheme(theme) },
    MuiSelect: { ...SelectTheme(theme) },
    MuiSkeleton: { ...SkeletonTheme(theme) },
    MuiSpeedDial: { ...SpeedDialTheme(theme) },
    MuiSpeedDialAction: { ...SpeedDialActionTheme(theme) },
    MuiSpeedDialIcon: { ...SpeedDialIconTheme(theme) },
    MuiSnackbar: { ...SnackbarTheme(theme) },
    MuiSnackbarContent: { ...SnackbarContentTheme(theme) },
    MuiSlider: { ...SliderTheme(theme) },
    MuiStack: { ...StackTheme(theme) },
    MuiStep: { ...StepTheme(theme) },
    MuiStepButton: { ...StepButtonTheme(theme) },
    MuiStepConnector: { ...StepConnectorTheme(theme) },
    MuiStepContent: { ...StepContentTheme(theme) },
    MuiStepIcon: { ...StepIconTheme(theme) },
    MuiStepLabel: { ...StepLabelTheme(theme) },
    MuiStepper: { ...StepperTheme(theme) },
    MuiSvgIcon: { ...SvgIconTheme(theme) },
    MuiSwitch: { ...SwitchTheme(theme) },
    MuiSwipeableDrawer: { ...SwipeableDrawerTheme(theme) },
    MuiTextField: { ...TextFieldTheme(theme) },
    MuiTab: { ...TabTheme(theme) },
    MuiTabs: { ...TabsTheme(theme) },
    MuiTable: { ...TableTheme(theme) },
    MuiTableBody: { ...TableBodyTheme(theme) },
    MuiTableCell: { ...TableCellTheme(theme) },
    MuiTableContainer: { ...TableContainerTheme(theme) },
    MuiTableFooter: { ...TableFooterTheme(theme) },
    MuiTableHead: { ...TableHeadTheme(theme) },
    MuiTablePagination: { ...TablePaginationTheme(theme) },
    MuiTableRow: { ...TableRowTheme(theme) },
    MuiTableSortLabel: { ...TableSortLabelTheme(theme) },
    MuiToggleButton: { ...ToggleButtonTheme(theme) },
    MuiToggleButtonGroup: { ...ToggleButtonGroupTheme(theme) },
    MuiToolbar: { ...ToolbarTheme(theme) },
    // MuiTooltip: { ...TooltipTheme(theme) },
    // MuiTypography: { ...TypographyTheme(theme) },
    MuiCssBaseline: {
      styleOverrides: () => ({}),
    },
  };
};

export const overrideTheme = {
  ...defaultTheme,
  components: {
    ...overrideComponents(defaultTheme),
  },
};

// Create a theme instance.
export const theme = createTheme(overrideTheme);

// process.env.NODE_ENV !== `production` &&
//   console.log(theme, '===================theme');
